---
language: node_js
node_js:
  - "8.0.0"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  - npm config set registry http://registry.npmjs.org/
  - npm config set spin false
install:
  - npm install
script:
  - npm test
notifications:
  email: false
